### PR TITLE
Ensure pietestgui is installed

### PR DESCRIPTION
**Pull request by cwilling**
Signed-off-by: Christoph Willing <chris.willing@linux.com>

### CODE REVIEW

**Comment by cwilling** [comment]
The current 'configure/make/make install' omits installing pietestgui. This PR adds pietestgui to the installation list.

**Comment by michaelhatPIengineering** [comment]
I would be happy to merge this but there are conflicts. 


<<<<<<< gui-executable
TARGET_LINK_LIBRARIES(pietestgui
	Qt5::Core
	Qt5::Gui
	Qt5::Widgets
	piehid
)

INSTALL(TARGETS pietestgui
    RUNTIME DESTINATION bin
)
=======
INSTALL(FILES pietestgui.desktop DESTINATION share/applications)
>>>>>>> master

how to I resolve them so I can merge? 

Sorry, my life is usually at the USB byte level, where my only task is to manage 36 bytes.

Michael

**Comment by cwilling** [comment]
I'm not sure but it may be because #9 was applied before #7. I'll reload what's in the repo right now and make a new PR. Leave this one as it is - I think I can make the changes in place. If not, I'll just submit a new PR.

**Comment by michaelhatPIengineering** [comment]
ok thanks

Sorry I got it in the wrong order...



________________________________

**Comment by cwilling** [comment]
Actually, it wasn't the ordering. It was because I made changes to the same file in different PRs, so my mistake.

I've fixed it now so should be OK to merge.

**Pull request merged**
